[-feature] Updating catalogues with latest Sympa modifications.
git-svn-id: https://subversion.renater.fr/sympa/branches/sympa-6.0-branch@6247 05aa8bb8-cd2b-0410-b1d7-8918dfa770ce

diff --git a/po/Makefile.in.in b/po/Makefile.in.in
--- a/po/Makefile.in.in
+++ b/po/Makefile.in.in
@@ -303,7 +303,7 @@ mostlyclean:
 clean: mostlyclean
 
 distclean: clean
-	rm -f Makefile Makefile.in POTFILES *.mo
+	rm -f Makefile Makefile.in POTFILES *.mo *.new.po
 
 maintainer-clean: distclean
 	@echo "This command is intended for maintainers to use;"
@@ -354,6 +354,25 @@ update-po: Makefile
 
 # General rule for updating PO files.
 
+.nop.po-clean:
+	@lang=`echo $@ | sed -e 's/\.po-update$$//'`; \
+	if test "$(PACKAGE)" = "gettext-tools"; then PATH=`pwd`/../src:$$PATH; fi; \
+	tmpdir=`pwd`; \
+	echo "$$lang:"; \
+	test "$(srcdir)" = . && cdcmd="" || cdcmd="cd $(srcdir) && "; \
+	echo "$${cdcmd}$(MSGMERGE) $$lang.po $(DOMAIN).pot -o $$lang.new.po"; \
+	cd $(srcdir); \
+	if $(MSGMERGE) $$lang.po $(DOMAIN).pot -o $$tmpdir/$$lang.new.po; then \
+	  if cmp $$lang.po $$tmpdir/$$lang.new.po >/dev/null 2>&1; then \
+	    rm -f $$tmpdir/$$lang.new.po; \
+	  else \
+            $(MSGCAT) --use-first -o $$tmpdir/$$lang.new.po $$tmpdir/$$lang.new.po $$lang.po; \
+	  fi; \
+	else \
+	  echo "msgmerge for $$lang.po failed!" 1>&2; \
+	  rm -f $$tmpdir/$$lang.new.po; \
+	fi
+
 .nop.po-update:
 	@lang=`echo $@ | sed -e 's/\.po-update$$//'`; \
 	if test "$(PACKAGE)" = "gettext-tools"; then PATH=`pwd`/../src:$$PATH; fi; \
@@ -377,6 +396,34 @@ update-po: Makefile
 	  echo "msgmerge for $$lang.po failed!" 1>&2; \
 	  rm -f $$tmpdir/$$lang.new.po; \
 	fi
+
+## Prepare a tar.gz with a structure adapted to Pootle
+## ie made of subdirectories (ll/sympa.po...templates/sympa.pot
+export:
+	echo "Building /tmp/sympa-po.tar.gz..."; \
+	if [ -d  /tmp/sympa-po ]; then \
+		rm -rf /tmp/sympa-po; \
+	fi
+	mkdir /tmp/sympa-po; \
+	mkdir /tmp/sympa-po/sympa; \
+	mkdir /tmp/sympa-po/web_help; \
+	mkdir /tmp/sympa-po/terminology; \
+	catalogs='$(CATALOGS)'; \
+	for cat in $$catalogs; do \
+	  cat=`basename $$cat`; \
+	  lang=`echo $$cat | sed -e 's/\.gmo$$//'`; \
+          mkdir /tmp/sympa-po/sympa/$$lang; \
+	  cp $$lang.po /tmp/sympa-po/sympa/$$lang/sympa.po; \
+	  mkdir /tmp/sympa-po/web_help/$$lang; \
+	  cp ../po-wwsympa/$$lang.po /tmp/sympa-po/web_help/$$lang/web_help.po; \
+	done
+	mkdir /tmp/sympa-po/sympa/templates; \
+	mkdir /tmp/sympa-po/web_help/templates; \
+	mkdir /tmp/sympa-po/terminology/templates; \
+	cp sympa.pot /tmp/sympa-po/sympa/templates/sympa.pot; \
+	cp ../po-wwsympa/web_help.pot /tmp/sympa-po/web_help/templates/web_help.pot; \
+	cp terminology.pot /tmp/sympa-po/terminology/templates/terminology.pot; \
+	(cd /tmp/sympa-po; tar -zcvf /tmp/sympa-po.tar.gz *)
 
 $(DUMMYPOFILES):
 
