[feature] Restoring the export and clean-po Makefile directives. This is mandatory to maintaint the several translations of Sympa, though it never needs to be used by Sympa users.
git-svn-id: https://subversion.renater.fr/sympa/branches/sympa-6.0-branch@6250 05aa8bb8-cd2b-0410-b1d7-8918dfa770ce

diff --git a/po/Makefile.in.in b/po/Makefile.in.in
--- a/po/Makefile.in.in
+++ b/po/Makefile.in.in
@@ -354,25 +354,6 @@ update-po: Makefile
 
 # General rule for updating PO files.
 
-.nop.po-clean:
-	@lang=`echo $@ | sed -e 's/\.po-update$$//'`; \
-	if test "$(PACKAGE)" = "gettext-tools"; then PATH=`pwd`/../src:$$PATH; fi; \
-	tmpdir=`pwd`; \
-	echo "$$lang:"; \
-	test "$(srcdir)" = . && cdcmd="" || cdcmd="cd $(srcdir) && "; \
-	echo "$${cdcmd}$(MSGMERGE) $$lang.po $(DOMAIN).pot -o $$lang.new.po"; \
-	cd $(srcdir); \
-	if $(MSGMERGE) $$lang.po $(DOMAIN).pot -o $$tmpdir/$$lang.new.po; then \
-	  if cmp $$lang.po $$tmpdir/$$lang.new.po >/dev/null 2>&1; then \
-	    rm -f $$tmpdir/$$lang.new.po; \
-	  else \
-            $(MSGCAT) --use-first -o $$tmpdir/$$lang.new.po $$tmpdir/$$lang.new.po $$lang.po; \
-	  fi; \
-	else \
-	  echo "msgmerge for $$lang.po failed!" 1>&2; \
-	  rm -f $$tmpdir/$$lang.new.po; \
-	fi
-
 .nop.po-update:
 	@lang=`echo $@ | sed -e 's/\.po-update$$//'`; \
 	if test "$(PACKAGE)" = "gettext-tools"; then PATH=`pwd`/../src:$$PATH; fi; \
@@ -385,12 +366,7 @@ update-po: Makefile
 	  if cmp $$lang.po $$tmpdir/$$lang.new.po >/dev/null 2>&1; then \
 	    rm -f $$tmpdir/$$lang.new.po; \
 	  else \
-	    if mv -f $$tmpdir/$$lang.new.po $$lang.po; then \
-	      :; \
-	    else \
-	      echo "msgmerge for $$lang.po failed: cannot move $$tmpdir/$$lang.new.po to $$lang.po" 1>&2; \
-	      exit 1; \
-	    fi; \
+            $(MSGCAT) --use-first -o $$tmpdir/$$lang.new.po $$tmpdir/$$lang.new.po $$lang.po; \
 	  fi; \
 	else \
 	  echo "msgmerge for $$lang.po failed!" 1>&2; \
@@ -424,6 +400,35 @@ export:
 	cp ../po-wwsympa/web_help.pot /tmp/sympa-po/web_help/templates/web_help.pot; \
 	cp terminology.pot /tmp/sympa-po/terminology/templates/terminology.pot; \
 	(cd /tmp/sympa-po; tar -zcvf /tmp/sympa-po.tar.gz *)
+
+clean-po: 
+	$(MAKE) $(DOMAIN).pot-update
+	@languages=`echo $(POFILES) | sed -e 's/\.po//g'`;\
+	for lang in $$languages; do \
+	  if test "$(PACKAGE)" = "gettext-tools"; then PATH=`pwd`/../src:$$PATH; fi; \
+	  tmpdir=`pwd`; \
+	  echo "$$lang:"; \
+	  test "$(srcdir)" = . && cdcmd="" || cdcmd="cd $(srcdir) && "; \
+	  echo "$${cdcmd}$(MSGMERGE) $$lang.po $(DOMAIN).pot -o $$lang.new.po"; \
+	  cd $(srcdir); \
+	  if $(MSGMERGE) $$lang.po $(DOMAIN).pot -o $$tmpdir/$$lang.new.po; then \
+	    if cmp $$lang.po $$tmpdir/$$lang.new.po >/dev/null 2>&1; then \
+	      rm -f $$tmpdir/$$lang.new.po; \
+	    else \
+	      if mv -f $$tmpdir/$$lang.new.po $$lang.po; then \
+	        :; \
+	      else \
+	        echo "msgmerge for $$lang.po failed: cannot move $$tmpdir/$$lang.new.po to $$lang.po" 1>&2; \
+	        exit 1; \
+	      fi; \
+	    fi; \
+	  else \
+	    echo "msgmerge for $$lang.po failed!" 1>&2; \
+	    rm -f $$tmpdir/$$lang.new.po; \
+	  fi;\
+        done;\
+        msgen en_US.po -o en_US.po;\
+
 
 $(DUMMYPOFILES):
 
